#!/bin/bash
#: Set analytics
#: 
#: Syntax:
#: brew tap-analytics [enable | disable]
analytics=$(cat ~/.tap-analytics-brew 2>/dev/null)
if [[ "" == $analytics ]]
then
  echo "This tap uses analytics. To disable analytics, run 'brew tap-analytics disable'. To enable, run 'brew analytics enable'."
  echo "enabled" > ~/.tap-analytics-brew
  analytics=$(cat ~/.tap-analytics-brew 2>/dev/null)
fi
if [[ "" == $1 ]]
then
  echo "Analytics is $analytics"
  exit 0
fi
if [[ "enable" == $1 ]]
then
  echo "enabled" > ~/.tap-analytics-brew
  exit 0
fi
if [[ "disable" == $1 ]]
then
  echo "disabled" > ~/.tap-analytics-brew
  exit 0
fi
